SiteSerralheriaSantos/Controllers/EquipeController.cs
using PagedList;
using SiteSerralheriaSantos.Help;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class EquipeController : Controller
    {
        private readonly Equipe _equipe;
        private readonly Imagem _imagem;
        private readonly Usuario _usuario;
        private readonly Empresa _empresa;
        private readonly Mensagem _mensagem;

        public EquipeController()
        {
            _equipe = new Equipe();
            _imagem = new Imagem();
            _usuario = new Usuario();
            _empresa = new Empresa();
            _mensagem = new Mensagem();
        }

        public ActionResult Index(int pagina = 1)
        {
            ViewBag.EmpresaId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorEquipe = 8;
            var equipes = _equipe.BuscarTodos();
            var lista = new List<Equipe>();
            lista.AddRange(equipes);
            return View(lista.ToPagedList(pagina, itensPorEquipe));
        }

        public ActionResult Adicionar()
        {
            ViewBag.Empresas = new SelectList(_empresa.BuscarTodos(), "EmpresaId", "Nome");
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Equipe equipe, HttpPostedFileBase fotoEquipe)
        {
            if (!ModelState.IsValid) return View(equipe).Error();
            if (fotoEquipe != null)
            {
                var nomeDaImgEquipe = Path.GetFileName(fotoEquipe.FileName);
                var pathEquipe = Path.Combine(Server.MapPath("~/Uploads/equipe/"), nomeDaImgEquipe);
                fotoEquipe.SaveAs(pathEquipe);
                var imagem = new Imagem();
                imagem.Url = imagem.CaminhoImgEquipe(fotoEquipe.FileName);
                imagem.ImagemId = Guid.NewGuid();
                _imagem.Adicionar(imagem);
                equipe.ImagemId = imagem.ImagemId;
                var entId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
                equipe.EmpresaId = (entId == Guid.Empty || entId == null) ? equipe.EmpresaId : (Guid)entId;
                _equipe.Adicionar(equipe);
                return RedirectToAction("Index").Success("Integrante da equipe adicionado com sucesso.");
            }
            else
            {
                return View(equipe).Error();
            }
        }

        public ActionResult Atualizar(Guid equipeId)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View(_equipe.BuscarPorId(equipeId));
        }

        [HttpPost]
        public ActionResult Atualizar(Equipe equipe, HttpPostedFileBase fotoEquipe)
        {
            if (!ModelState.IsValid) return View(equipe).Error();
            if (fotoEquipe == null)
            {
                _equipe.Atualizar(equipe);
                return RedirectToAction("Atualizar", new { projetoId = equipe.EquipeId }).Success("Integrante da equipe atualizado com sucesso.");
            }
            else
            {
                var nomeDaImgEquipe = Path.GetFileName(fotoEquipe.FileName);
                var pathEquipe = Path.Combine(Server.MapPath("~/Uploads/equipe/"), nomeDaImgEquipe);
                fotoEquipe.SaveAs(pathEquipe);
                var imagem = _imagem.BuscarPorId(equipe.ImagemId);
                imagem.Url = imagem.CaminhoImgEquipe(fotoEquipe.FileName);
                _imagem.Atualizar(imagem);
                _equipe.Atualizar(equipe);
                return RedirectToAction("Atualizar", new { projetoId = equipe.EquipeId }).Success("Integrante da equipe atualizado com sucesso.");
            }
        }

        public ActionResult Ativo(Guid equipeId, int pagina)
        {
            var equipeAtual = _equipe.BuscarPorId(equipeId);
            equipeAtual.AtivarOuDesativar();
            _equipe.Atualizar(equipeAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var equipes = _equipe.BuscarTodos();
            var lista = new List<Equipe>();
            lista.AddRange(equipes);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarEquipe(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var equipes = _equipe.BuscarTodosPorEquipe(textoDigitado);
            var lista = new List<Equipe>();
            lista.AddRange(equipes);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

SiteSerralheriaSantos/Controllers/LoginController.cs
using PagedList;
using SiteSerralheriaSantos.Help;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.Utils;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class LoginController : Controller
    {
        private readonly Usuario _usuario;
        private readonly Empresa _empresa;
        private readonly Mensagem _mensagem;
        
        public LoginController()
        {
            _usuario = new Usuario();
            _empresa = new Empresa();
            _mensagem = new Mensagem();
        }

        [Authorize]
        public ActionResult Index(int pagina = 1)
        {
            ViewBag.EmpresaId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var membrosDaEquipes = _usuario.BuscarTodos();
            var lista = new List<Usuario>();
            lista.AddRange(membrosDaEquipes);
            return View(lista.ToPagedList(pagina, itensPorPagina));
        }

        [Authorize]
        public ActionResult Adicionar()
        {
            ViewBag.Empresas = new SelectList(_empresa.BuscarTodos(), "EmpresaId", "Nome");
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Adicionar(CadastrarUsuarioVm usuario)
        {
            if (!ModelState.IsValid) return View(usuario).Error("Erro ao cadastrar usuário!");
            if (_usuario.BuscarTodos().Count(u => u.Login == usuario.Login) > 0) return View(usuario).Error("Esse login já está em uso");
            var usu = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            var empresaId = (usu == Guid.Empty || usu == null) ? usuario.EmpresaId : usu;
            Usuario novoUsuario = new Usuario
            {
                Nome = usuario.Nome,
                Login = usuario.Login,
                Senha = Hash.GerarHash(usuario.Senha),
                EmpresaId = empresaId,
                Ativo = true,
                TipoUsuario = usuario.TipoUsuario
            };
            _usuario.Adicionar(novoUsuario);
            return RedirectToAction("Index").Success("Usuário cadastrado com sucesso!");
        }

        public ActionResult Atualizar(Guid usuarioId)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View(_usuario.BuscarPorId(usuarioId));
        }

        [HttpPost]
        public ActionResult Atualizar(Usuario usuario)
        {
            if (!ModelState.IsValid) return View().Error("Erro ao atualizar usuário");
            _usuario.Atualizar(usuario);
            return RedirectToAction("Index").Success("Sistema atualizado com sucesso");
        }

        [HttpPost]
        public ActionResult Entrar(LoginVm loginVm)
        {
            if (!ModelState.IsValid) return RedirectToAction("Index", "Home").Error("Erro ao fazer login!");
            if (loginVm == null) return RedirectToAction("Index", "Home").Error("Preencha todos os campos!");
            var usuario = _usuario.BuscarPorLogin(loginVm.Login);
            if (usuario == null) return RedirectToAction("Index", "Home").Error("Este usuário não existe!");
            if (usuario.Ativo != true) return RedirectToAction("Index", "Home").Error("Este usuário está desativado!");
            if (usuario.Senha != Hash.GerarHash(loginVm.Senha)) return RedirectToAction("Index", "Home").Error("Senha incorreta!");
            var identity = new ClaimsIdentity(new[]
            {
                new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider","ASP.NET Identity"),
                new Claim(ClaimTypes.NameIdentifier, usuario.UsuarioId.ToString()),
                new Claim(ClaimTypes.Name, usuario.Nome),
                new Claim(ClaimTypes.Role, usuario.TipoUsuario.ToString()),
            }, "ApplicationCookie");
            Request.GetOwinContext().Authentication.SignIn(identity);

            if (!String.IsNullOrWhiteSpace(loginVm.UrlRetorno) || Url.IsLocalUrl(loginVm.UrlRetorno)) return Redirect(loginVm.UrlRetorno);

            if (usuario.Empresa == null && (usuario.TipoUsuario == TipoUsuario.Administrador || usuario.TipoUsuario == TipoUsuario.Usuario))
                return RedirectToAction("Adicionar", "Empresa").Information($"Bem vindo {usuario.Nome}");
            else if (usuario.Empresa != null && (usuario.TipoUsuario == TipoUsuario.Administrador || usuario.TipoUsuario == TipoUsuario.Usuario))
                return RedirectToAction("Atualizar", "Empresa", new { empresaId = usuario.Empresa.EmpresaId }).Information($"Bem vindo {usuario.Nome}");
            else
                return RedirectToAction("Index", "Empresa").Information($"Bem vindo {usuario.Nome}");
        }

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut("ApplicationCookie");
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public ActionResult AlterarSenha()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaVm altrSenha)
        {
            if (!ModelState.IsValid) return View(altrSenha).Error("Erro ao alterar senha!");
            var usuario = _usuario.BuscarPorId(Account.UsuarioId);
            usuario.Senha = Hash.GerarHash(altrSenha.NovaSenha);
            _usuario.Atualizar(usuario);
            return View().Success("Senha atualizada com sucesso!");
        }

        public ActionResult Ativo(Guid usuarioId, int pagina)
        {
            var usuarioAtual = _usuario.BuscarPorId(usuarioId);
            usuarioAtual.AtivarOuDesativar();
            _usuario.Atualizar(usuarioAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var usuarios = _usuario.BuscarTodos();
            var lista = new List<Usuario>();
            lista.AddRange(usuarios);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarUsuario(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 5;
            var usuarios = _usuario.BuscarTodosPorNome(textoDigitado);
            var lista = new List<Usuario>();
            lista.AddRange(usuarios);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

SiteSerralheriaSantos/Controllers/ProjetoController.cs
using PagedList;
using SiteSerralheriaSantos.Help;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly Galeria _galeria;
        private readonly Imagem _imagem;
        private readonly Categoria _categoria;
        private readonly Usuario _usuario;
        private readonly Empresa _empresa;
        private readonly Mensagem _mensagem;

        public ProjetoController()
        {
            _galeria = new Galeria();
            _imagem = new Imagem();
            _categoria = new Categoria();
            _usuario = new Usuario();
            _empresa = new Empresa();
            _mensagem = new Mensagem();
        }

        public ActionResult Index(int pagina = 1)
        {
            ViewBag.EmpresaId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorProjeto = 8;
            var projetos = _galeria.BuscarTodos();
            var lista = new List<Galeria>();
            lista.AddRange(projetos);
            return View(lista.ToPagedList(pagina, itensPorProjeto));
        }

        public ActionResult Adicionar()
        {
            ViewBag.Categorias = new SelectList(_categoria.BuscarTodos(), "CategoriaId", "Nome");
            ViewBag.Empresas = new SelectList(_empresa.BuscarTodos(), "EmpresaId", "Nome");
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Galeria galeria, HttpPostedFileBase fotoProjeto)
        {
            if (!ModelState.IsValid) return View(galeria).Error();
            if (fotoProjeto != null)
            {
                var nomeDaImgProjeto = Path.GetFileName(fotoProjeto.FileName);
                var pathProjeto = Path.Combine(Server.MapPath("~/Uploads/galeria/"), nomeDaImgProjeto);
                fotoProjeto.SaveAs(pathProjeto);
                var imagem = new Imagem();
                imagem.Url = imagem.CaminhoImgGaleria(fotoProjeto.FileName);
                imagem.ImagemId = Guid.NewGuid();
                _imagem.Adicionar(imagem);
                galeria.ImagemId = imagem.ImagemId;
                var entId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
                galeria.EmpresaId = (entId == Guid.Empty || entId == null) ? galeria.EmpresaId : (Guid)entId;
                _galeria.Adicionar(galeria);
                return RedirectToAction("Index").Success();
            }
            else
            {
                return View(galeria).Error();
            }
        }

        public ActionResult Atualizar(Guid projetoId)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            ViewBag.Categorias = new SelectList(_categoria.BuscarTodos(), "CategoriaId", "Nome");
            return View(_galeria.BuscarPorId(projetoId));
        }

        [HttpPost]
        public ActionResult Atualizar(Galeria galeria, HttpPostedFileBase fotoProjeto)
        {
            if (!ModelState.IsValid) return View(galeria).Error();
            if (fotoProjeto == null)
            {
                _galeria.Atualizar(galeria);
                return RedirectToAction("Atualizar", new { projetoId = galeria.GaleriaId }).Success();
            }
            else
            {
                var nomeDaImgProjeto = Path.GetFileName(fotoProjeto.FileName);
                var pathProjeto = Path.Combine(Server.MapPath("~/Uploads/galeria/"), nomeDaImgProjeto);
                fotoProjeto.SaveAs(pathProjeto);
                var imagem = _imagem.BuscarPorId(galeria.ImagemId);
                imagem.Url = imagem.CaminhoImgGaleria(fotoProjeto.FileName);
                _imagem.Atualizar(imagem);
                _galeria.Atualizar(galeria);
                return RedirectToAction("Atualizar", new { projetoId = galeria.GaleriaId }).Success();
            }
        }

        public ActionResult Ativo(Guid projetoId, int pagina)
        {
            var projetoAtual = _galeria.BuscarPorId(projetoId);
            projetoAtual.AtivarOuDesativar();
            _galeria.Atualizar(projetoAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var projetos = _galeria.BuscarTodos();
            var lista = new List<Galeria>();
            lista.AddRange(projetos);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarProjeto(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var projetos = _galeria.BuscarTodosPorGaleria(textoDigitado);
            var lista = new List<Galeria>();
            lista.AddRange(projetos);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public ActionResult AbrirModalAdicionarCategoria()
        {
            return PartialView("_ModalAdicionarCategoria");
        }

        [HttpPost]
        public void AdicionarCategoria(Categoria categoria)
        {
            _categoria.Adicionar(categoria);
        }
    }
}

SiteSerralheriaSantos/Views/Shared/_Footer.cshtml
@using SiteSerralheriaSantos.Models

@{
    var empresa = (Empresa)ViewBag.Empresa;
}
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                @if (empresa.EmpresaId != Guid.Empty)
                {
                    <div class="col-lg-5 col-md-6 footer-info">
                        <h4>Informátivo</h4>
                        <p>@empresa.Informativo</p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Menu Rápido</h4>
                        <ul>
                            <li><a href="@Url.Action("Index","Home")">Início</a></li>
                            <li><a href="@Url.Action("Projetos","Home")">Projetos</a></li>
                            <li><a href="@Url.Action("SobreNos","Home")">Sobre Nós</a></li>
                            <li><a href="@Url.Action("Parceiros","Home")">Parceiros</a></li>
                            <li><label id="lb-modal" class="btn-abrirModal" data-abrirmodal="@Url.Action("AbrirModalLogin", "Home", new { })">Entrar</label></li>
                        </ul>
                    </div>

                    <div class="col-lg-5 col-md-6 footer-contact ">
                        <h4>Contatos</h4>
                        @if (empresa.Enderecos != null && empresa.Enderecos.Any())
                        {
                            <p>
                                @foreach (var item in empresa.Enderecos)
                                {
                                    @item.FormatEndereco<br>
                                }
                                <strong>Email: </strong>@empresa.Email<br>
                                <strong>Celular: </strong> @empresa.Celular<br>
                                <strong>Telefone: </strong> @empresa.Telefone<br>
                            </p>
                        }
                        @if (empresa.RedesSociais != null && empresa.RedesSociais.Any())
                        {
                            <div class="social-links">
                                @foreach (var item in empresa.RedesSociais)
                                {
                                    <a href="@item.Link" class="@Enum.GetName(typeof(TipoRedeSocial), item.TipoRedeSocial)"><i class="fa fa-@Enum.GetName(typeof(TipoRedeSocial), item.TipoRedeSocial)"></i></a>
                                }
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong>@DateTime.Now.Year</strong>. Todos os direitos reservados
        </div>
        <div class="credits">
            Desenvolvido por Eloenay Pereira.
        </div>
    </div>
</footer>

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

<div class="btn-whats">
    <a href="https://wa.me/@empresa.CelularWhatsappFormat?text=@empresa.Nome" target="_blank">
        <button id="draggable" class="pulse-button">
            <i class="fa fa-whatsapp"></i>
        </button>
    </a>
</div>

SiteSerralheriaSantos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>SSS - @ViewBag.Title</title>
    <link href="imagem/favicon.png" rel="icon">
    <link href="imagem/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    @Styles.Render("~/Content/externo")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/notificacao")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="site-wrap">
        @Html.Partial("_Menu")
        <section id="intro" class="clearfix">
            <div class="container">

                <div class="intro-img">
                    <img src="../../imagem/intro_img.svg" alt="" class="img-fluid">
                </div>

                <div class="intro-info">
                    <h2>Solução<br>para sua obra</h2>

                </div>

            </div>
        </section>

        <main id="main">
            @RenderBody()
        </main>

        @Html.Partial("_Footer")

        @Scripts.Render("~/bundles/externo")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/notificacao")
        @RenderSection("scripts", required: false)
        @Html.Partial("_Message")
    </div>

</body>
</html>

SiteSerralheriaSantos/Views/Shared/_LayoutInterno.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>SSS - @ViewBag.Title</title>
    <link href="imagem/favicon.png" rel="icon">
    <link href="imagem/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    @Styles.Render("~/Content/externo")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/notificacao")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="site-wrap">
        @Html.Partial("_MenuInterno")

        <main id="main">
            @RenderBody()
        </main>

        @Scripts.Render("~/bundles/externo")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/notificacao")
        @RenderSection("scripts", required: false)
        @Html.Partial("_Message")
    </div>

</body>
</html>

SiteSerralheriaSantos/Views/Shared/_Menu.cshtml
@using SiteSerralheriaSantos.Models
@{
    var empresa = (Empresa)ViewBag.Empresa;
}
<header id="header" class="fixed-top">
    <div class="container">
        <div class="logo float-left">
            @if (empresa.EmpresaId != Guid.Empty)
            {
                <a href="@Url.Action("Index","Home")" class="scrollto"><img src="@empresa.Imagem.Url" alt="" class="img-fluid"></a>
            }
        </div>
        <nav class="main-nav float-right d-none d-lg-block">
            <ul>
                <li class=""><a href="@Url.Action("Index","Home")">Início</a></li>
                <li><a href="@Url.Action("Projetos","Home")">Projetos</a></li>
                <li><a href="@Url.Action("SobreNos","Home")">Sobre Nós</a></li>
                <li><a href="@Url.Action("Parceiros","Home")">Parceiros</a></li>
                @if (empresa.EmpresaId == Guid.Empty)
                {
                    <li><a href="#" id="lb-modal" class="btn-abrirModal" data-abrirmodal="@Url.Action("AbrirModalLogin", "Home", new { })">Entrar</a></li>
                }
            </ul>
        </nav>
    </div>
</header>

SiteSerralheriaSantos/Views/Shared/_MenuInterno.cshtml
@using SiteSerralheriaSantos.ViewModels
@using SiteSerralheriaSantos.Models
@{
    var empresa = (Empresa)ViewBag.Empresa;
    var msgNaoVisualizada =  (int)ViewBag.Mensagem;
}
<header id="header" class="fixed-top">
    <div class="container">

        <div class="logo float-left">
            @if (Account.Roles == "Master")
            {
                <a href="@Url.Action("Index","Empresa")" class="scrollto"><h3>MASTER</h3></a>
            }
            else if (empresa != null && Account.Roles != "Master")
            {
                <a href="@Url.Action("AddOrUpdate","Empresa")" class="scrollto"><img src="@empresa.Imagem.Url" alt="" class="img-fluid"></a>
            }
        </div>

        <nav class="main-nav float-right d-none d-lg-block">
            <ul>
                @if (Account.Roles == "Master")
                {
                    <li><a href="@Url.Action("Index", "Empresa")">Empresa</a></li>
                }
                else
                {
                    <li><a href="@Url.Action("AddOrUpdate", "Empresa")">Empresa</a></li>
                }
                <li><a href="@Url.Action("Index","Projeto")">Projeto</a></li>
                <li><a href="@Url.Action("Index","Parceiro")">Parceiro</a></li>
                <li><a href="@Url.Action("Index","Equipe")">Equipe</a></li>
                <li><a href="@Url.Action("Index","Mensagem")">Mensagem @if(msgNaoVisualizada > 0){<span class="badge badge-pill badge-danger">@msgNaoVisualizada</span>}</a></li>

                @if (Account.Roles == "Master")
                {
                    <li><a href="@Url.Action("Index","Login")">Usuário</a></li>
                }
                <li><a href="@Url.Action("Logout","Login")"><i class="fa fa-sign-out"></i> Sair</a></li>
                <li><a href="@Url.Action("AlterarSenha","Login")" title="Alterar senha"><span class="border-left pl-xl-4"></span>@User.Identity.Name</a></li>
            </ul>
        </nav>
    </div>
</header>

SiteSerralheriaSantos/Views/Shared/_Message.cshtml
@using SiteSerralheriaSantos.Help
@{
    var alerts = TempData.ContainsKey("Message") ? (List<Alert>)TempData["Message"] : new List<Alert>();
    if (alerts.Any())
    {
        <script>
            @{
               foreach (var item in alerts)
               {
                   @Html.Raw("swal('Mensagem','" + item.Message + "', '" + item.AlertStyle + "');")
               }
           }
        </script>
    }
}