SiteSerralheriaSantos/Models/Mensagem.cs
using SiteSerralheriaSantos.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteSerralheriaSantos.Models
{
    public class Mensagem
    {
        #region Atributos
        public Guid MensagemId { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Texto { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataDeEntrada { get; set; }
        public bool Visto { get; set; }
        #endregion

        #region Relacionamentos
        public Guid EmpresaId { get; set; }
        public Empresa Empresa { get; set; }
        #endregion

        #region Crud
        MensagemRepository _mensagemRepositorio = new MensagemRepository();
        public void Adicionar(Mensagem mensagem) => _mensagemRepositorio.Adicionar(mensagem);
        public void Atualizar(Mensagem mensagem) => _mensagemRepositorio.Atualizar(mensagem);
        public Mensagem BuscarPorId(Guid mensagemId) => _mensagemRepositorio.BuscarPorId(mensagemId);
        public IEnumerable<Mensagem> BuscarTodosPorData(DateTime data) => _mensagemRepositorio.BuscarTodosPorData(data);
        public IEnumerable<Mensagem> BuscarTodosPorMensagem(string textoDigitado) => _mensagemRepositorio.BuscarTodosPorMensagem(textoDigitado);
        public IEnumerable<Mensagem> BuscarTodos() => _mensagemRepositorio.BuscarTodos();
        public int QntDeMsgNaoVisualizada() => _mensagemRepositorio.QntDeMsgNaoVisualizada();
        #endregion
    }
}

SiteSerralheriaSantos/Controllers/MensagemController.cs
using PagedList;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class MensagemController : Controller
    {
        private readonly Mensagem _mensagem;
        private readonly Empresa _empresa;
        private readonly Usuario _usuario;

        public MensagemController()
        {
            _mensagem = new Mensagem();
            _empresa = new Empresa();
            _usuario = new Usuario();
        }

        public ActionResult Index(int pagina = 1)
        {
            ViewBag.EmpresaId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var mensagens = _mensagem.BuscarTodos();
            var lista = new List<Mensagem>();
            lista.AddRange(mensagens);
            return View(lista.ToPagedList(pagina, itensPorPagina));
        }

        public ActionResult Descricao(Guid mensagemId)
        {
            var mensagem = _mensagem.BuscarPorId(mensagemId);
            mensagem.Visto = true;
            _mensagem.Atualizar(mensagem);
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View(mensagem);
        }

        public PartialViewResult BuscarMensagem(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var mensagens = _mensagem.BuscarTodosPorMensagem(textoDigitado);
            var lista = new List<Mensagem>();
            lista.AddRange(mensagens);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

SiteSerralheriaSantos/Views/Mensagem/Descricao.cshtml
@model SiteSerralheriaSantos.Models.Mensagem

@{
    ViewBag.Title = "Atualizar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

<section>
    <div class="container" style="margin-top:140px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3><i>Mensagem / Descrição</i></h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content" style="display: block;">
                            <br>
                            @Html.HiddenFor(x => x.MensagemId)
                            @Html.HiddenFor(x => x.EmpresaId)
                            <div class="row form-group">
                                <div class="col-md-6">
                                    @Html.Label("Nome")
                                    @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", disabled = "disabled" })
                                </div>
                                <div class="col-md-6">
                                    @Html.Label("Email")
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", disabled = "disabled" })
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-12">
                                    @Html.Label("Nome")
                                    @Html.TextAreaFor(model => model.Texto, new { @class = "form-control", disabled = "disabled" })
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col-md-6">
                                    <a href="@Url.Action("Index", "Mensagem", new { })" class="btn bg-secondary py-2 px-4 text-white">Retornar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SiteSerralheriaSantos/Views/Mensagem/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="page-title">
            <div class="title_left">
                <h3><i>Mensagens</i></h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" id="input-pesquisa" class="form-control" placeholder="Buscar por mensagem">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content" style="display: block;">
                        <br>
                        @Html.Partial("_PartialTabela")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/buscar-paginacao")
}

SiteSerralheriaSantos/Views/Mensagem/_PartialTabela.cshtml
@using SiteSerralheriaSantos.Models
@using PagedList.Mvc
@model PagedList.PagedList<Mensagem>

@{
    var paginaAtual = (int)TempData["Pagina"];
}
<div class="carregar-itens" data-url="@Url.Action("BuscarMensagem", "Mensagem", new { })">
    @if (Model != null && Model.Any())
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Data de Entrada</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DataDeEntrada)
                        </td>
                        <td>
                            @if (item.Visto == false)
                            {
                                <span class="badge badge-pill badge-secondary">Não visualizado</span>
                            }
                            else
                            {
                                <span class="badge badge-pill badge-success">visualizado</span>
                            }
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Descricao", new { mensagemId = item.MensagemId }, new { @class = "btn bg-secondary text-white rounded fa fa-list float-right ml-1 mb-1", data_toggle = "tooltip", Title = "Descricao" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-center">
            <h3>Nenhuma Informação Encontrada!</h3>
        </div>
    }
    <div class="row">
        <div class="col-12 mt-5">
            <div id="pageLink" data-tipo="menu" class="custom-pagination float-right" data-paginaatual="@paginaAtual" style="margin-top:-20px !important;">
                @Html.PagedListPager(Model, pagina => Url.Action("BuscarMensagem", "Mensagem", new { pagina = pagina }), new PagedListRenderOptions { LinkToPreviousPageFormat = "«", LinkToNextPageFormat = "»" })
            </div>
        </div>
    </div>
</div>