SiteSerralheriaSantos/Models/Parceiro.cs
using SiteSerralheriaSantos.Repository;
using System;
using System.Collections.Generic;

namespace SiteSerralheriaSantos.Models
{
    public class Parceiro
    {
        #region Atributos
        public Guid ParceiroId { get; set; }
        public string Nome { get; set; }
        public string Link { get; set; }
        public bool Ativo { get; set; } = true;
        #endregion

        #region Relacionamentos
        public Guid EmpresaId { get; set; }
        public Empresa Empresa { get; set; }
        public Guid ImagemId { get; set; }
        public Imagem Imagem { get; set; }
        #endregion

        #region Crud
        ParceiroRepository _parceiroRepositorio = new ParceiroRepository();
        public void Adicionar(Parceiro parceiro) => _parceiroRepositorio.Adicionar(parceiro);
        public void Atualizar(Parceiro parceiro) => _parceiroRepositorio.Atualizar(parceiro);
        public Parceiro BuscarPorId(Guid parceiroId) => _parceiroRepositorio.BuscarPorId(parceiroId);
        public IEnumerable<Parceiro> BuscarTodos() => _parceiroRepositorio.BuscarTodos();
        public IEnumerable<Parceiro> BuscarTodosPorParceiro(string textoDigitado) => _parceiroRepositorio.BuscarTodosPorParceiro(textoDigitado);
        public IEnumerable<Parceiro> BuscarTodosPorEmpresa(Guid empresaId) => _parceiroRepositorio.BuscarTodosPorEmpresa(empresaId);
        #endregion

        #region Métodos
        public void AtivarOuDesativar()
        {
            Ativo = !Ativo;
        }
        #endregion
    }
}

SiteSerralheriaSantos/Controllers/ParceiroController.cs
using PagedList;
using SiteSerralheriaSantos.Help;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class ParceiroController : Controller
    {
        private readonly Parceiro _parceiro;
        private readonly Imagem _imagem;
        private readonly Usuario _usuario;
        private readonly Empresa _empresa;
        private readonly Mensagem _mensagem;

        public ParceiroController()
        {
            _parceiro = new Parceiro();
            _imagem = new Imagem();
            _usuario = new Usuario();
            _empresa = new Empresa();
            _mensagem = new Mensagem();
        }

        public ActionResult Index(int pagina = 1)
        {
            ViewBag.EmpresaId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var parceiros = _parceiro.BuscarTodos();
            var lista = new List<Parceiro>();
            lista.AddRange(parceiros);
            return View(lista.ToPagedList(pagina, itensPorPagina));
        }

        public ActionResult Adicionar()
        {
            ViewBag.Empresas = new SelectList(_empresa.BuscarTodos(), "EmpresaId", "Nome");
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Parceiro parceiro, HttpPostedFileBase fotoParceiro)
        {
            if (!ModelState.IsValid) return View(parceiro).Error("Erro ao cadastrar parceiro");
            if (fotoParceiro != null)
            {
                var nomeDaImgParceiro = Path.GetFileName(fotoParceiro.FileName);
                var pathParceiro = Path.Combine(Server.MapPath("~/Uploads/parceiro/"), nomeDaImgParceiro);
                fotoParceiro.SaveAs(pathParceiro);
                var imagem = new Imagem();
                imagem.Url = imagem.CaminhoImgParceiro(fotoParceiro.FileName);
                imagem.ImagemId = Guid.NewGuid();
                _imagem.Adicionar(imagem);
                parceiro.ImagemId = imagem.ImagemId;
                var entId = _usuario.BuscarPorId(Account.UsuarioId).EmpresaId;
                parceiro.EmpresaId = (entId == Guid.Empty || entId == null) ? parceiro.EmpresaId : (Guid)entId;
                _parceiro.Adicionar(parceiro);
                return RedirectToAction("Index").Success("Parceiro cadastrado com sucesso");
            }
            else
            {
                return View(parceiro).Error("Erro ao cadastrar parceiro");
            }
        }

        public ActionResult Atualizar(Guid parceiroId)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View(_parceiro.BuscarPorId(parceiroId));
        }

        [HttpPost]
        public ActionResult Atualizar(Parceiro parceiro, HttpPostedFileBase fotoParceiro)
        {
            if (!ModelState.IsValid) return View(parceiro).Error("Erro ao atualizar parceiro");
            if (fotoParceiro == null)
            {
                _parceiro.Atualizar(parceiro);
                return RedirectToAction("Atualizar", new { parceiroId = parceiro.ParceiroId }).Success("Parceiro atualizado com sucesso");
            }
            else
            {
                var nomeDaImgParceiro = Path.GetFileName(fotoParceiro.FileName);
                var pathParcero = Path.Combine(Server.MapPath("~/Uploads/parceiro/"), nomeDaImgParceiro);
                fotoParceiro.SaveAs(pathParcero);
                var imagem = _imagem.BuscarPorId(parceiro.ImagemId);
                imagem.Url = imagem.CaminhoImgParceiro(fotoParceiro.FileName);
                _imagem.Atualizar(imagem);
                _parceiro.Atualizar(parceiro);
                return RedirectToAction("Atualizar", new { parceiroId = parceiro.ParceiroId }).Success("Parceiro atualizado com sucesso");
            }
        }

        public ActionResult Ativo(Guid parceiroId, int pagina)
        {
            var parceiroAtual = _parceiro.BuscarPorId(parceiroId);
            parceiroAtual.AtivarOuDesativar();
            _parceiro.Atualizar(parceiroAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var parceiros = _parceiro.BuscarTodos();
            var lista = new List<Parceiro>();
            lista.AddRange(parceiros);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarParceiro(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var parceiros = _parceiro.BuscarTodosPorParceiro(textoDigitado);
            var lista = new List<Parceiro>();
            lista.AddRange(parceiros);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }
    }
}

SiteSerralheriaSantos/Views/Parceiro/Adicionar.cshtml
@model SiteSerralheriaSantos.Models.Parceiro

@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
@section styles{
    @Styles.Render("~/Content/carregar-imagem")
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3><i>Parceiro / Adicionar</i></h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content" style="display: block;">
                            <br>
                            @using (Html.BeginForm("Adicionar", "Parceiro", FormMethod.Post, new { @class = "p-3 bg-white form-color", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Partial("_Form")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/carregar-imagem")
}

SiteSerralheriaSantos/Views/Parceiro/Atualizar.cshtml
@model SiteSerralheriaSantos.Models.Parceiro

@{
    ViewBag.Title = "Atualizar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
@section styles{
    @Styles.Render("~/Content/carregar-imagem")
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3><i>Parceiro / Atualizar</i></h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content" style="display: block;">
                            <br>
                            @using (Html.BeginForm("Atualizar", "Parceiro", FormMethod.Post, new { @class = "p-3 bg-white form-color", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(x => x.ParceiroId);
                                @Html.HiddenFor(x => x.ImagemId);
                                @Html.HiddenFor(x => x.EmpresaId);
                                @Html.HiddenFor(x => x.Ativo);
                                @Html.Partial("_Form")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/carregar-imagem")
}

SiteSerralheriaSantos/Views/Parceiro/Index.cshtml
@using SiteSerralheriaSantos.ViewModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="page-title">
            <div class="title_left">
                <h3><i>Parceiros</i></h3>
            </div>
            <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" id="input-pesquisa" class="form-control" placeholder="Buscar por parceiro">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button"><span class="fa fa-search"></span></button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    @if (Account.Roles == "Master" || ViewBag.EmpresaId != null && Account.Roles != "Master")
                    {
                        <div class="x_title">
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    @Html.ActionLink("Adicionar", "Adicionar", null, new { @class = "btn bg-secondary text-white" })
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                    }
                    else
                    {
                        <b>Para adicionar um parceiro, deve existir uma empresa!</b>
                    }
                    <div class="x_content" style="display: block;">
                        <br>
                        @Html.Partial("_PartialTabela")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/buscar-paginacao")
    @Scripts.Render("~/bundles/evento-ativo")
}

SiteSerralheriaSantos/Views/Parceiro/_Form.cshtml
@using SiteSerralheriaSantos.ViewModels
@model SiteSerralheriaSantos.Models.Parceiro

<div class="row form-group">
    <div class="col-md-12">
        @Html.LabelFor(model => model.Nome, new { @class = "" })
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12">
        @Html.Label("Link")
        @Html.TextBoxFor(model => model.Link, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12">
        @Html.Label("Imagem Logo *")
        <div class="input-group image-preview">
            @if (Model == null || Model.ImagemId == null)
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="">
                <p style="font-size:9px;">Click dentro da caixa de texto</p>
            }
            else
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="@Url.Content(Model.Imagem.NomeImagemParceiro)">
                <p style="font-size:9px;">Click dentro da caixa de texto</p>
            }
            <span class="input-group-btn">
                <div class="btn btn-default image text-center">
                    <span class="glyphicon glyphicon-folder-open  glyphicon-align-center"></span>
                    <input type="file" name="fotoParceiro" accept="image/png, image/jpeg, image/jpg" />
                </div>
            </span>
        </div>
    </div>
</div>
@if (Model != null)
{
    <div class="row form-group">
        <div class="col-md-2 text-center div-img">
            <img class="img-carregada" src="@Model.Imagem.Url" />
            <h4>@Model.Imagem.NomeImagemParceiro</h4>
        </div>
    </div>
}
@if (Account.Roles == "Master")
{
    <div class="row form-group">
        <div class="col-md-12">
            @Html.Label("Empresa")
            <div class="input-group">
                @Html.DropDownListFor(model => model.EmpresaId, (SelectList)ViewBag.Empresas, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmpresaId, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<hr />
<div class="row form-group">
    <div class="col-md-6">
        <a href="@Url.Action("Index", "Parceiro", new { })" class="btn bg-secondary py-2 px-4 text-white">Retornar</a>
    </div>
    <div class="col-md-6 text-right">
        <input type="submit" value="Salvar" class="btn bg-secondary py-2 px-4 text-white">
    </div>
</div>

SiteSerralheriaSantos/Views/Parceiro/_PartialTabela.cshtml
@using SiteSerralheriaSantos.Models
@using PagedList.Mvc
@model PagedList.PagedList<Parceiro>

@{
    var paginaAtual = (int)TempData["Pagina"];
}
<div class="carregar-itens" data-url="@Url.Action("BuscarParceiro", "Parceiro", new { })">
    @if (Model != null && Model.Any())
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Atualizar", new { parceiroId = item.ParceiroId }, new { @class = "btn bg-secondary text-white rounded fa fa-pencil float-right ml-1 mb-1", data_toggle = "tooltip", Title = "Atualizar" })

                            @if (item.Ativo == true)
                            {
                                <button type="button" id="btn-ativo" data-ativo="@Url.Action("Ativo", "Parceiro", new { parceiroId = item.ParceiroId })" class="btn bg-secondary text-white rounded fa fa-close fa float-right ml-1 mb-1" data-toggle="tooltip" title="Desativar"></button>
                            }
                            else
                            {
                                <button type="button" id="btn-ativo" data-ativo="@Url.Action("Ativo", "Parceiro", new { parceiroId = item.ParceiroId })" class="btn bg-secondary text-white rounded fa fa-check float-right ml-1 mb-1" data-toggle="tooltip" title="Ativar"></button>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="text-center">
            <h3>Nenhuma Informação Encontrada!</h3>
        </div>
    }
    <div class="row">
        <div class="col-12 mt-5">
            <div id="pageLink" data-tipo="menu" class="custom-pagination float-right" data-paginaatual="@paginaAtual" style="margin-top:-20px !important;">
                @Html.PagedListPager(Model, pagina => Url.Action("BuscarParceiro", "Parceiro", new { pagina = pagina }), new PagedListRenderOptions { LinkToPreviousPageFormat = "«", LinkToNextPageFormat = "»" })
            </div>
        </div>
    </div>
</div>