SiteSerralheriaSantos/Models/Empresa.cs
using SiteSerralheriaSantos.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SiteSerralheriaSantos.Models
{
    public class Empresa
    {
        #region Atributos
        public Guid EmpresaId { get; set; }
        public string Nome { get; set; }
        public string Celular { get; set; }
        public string CelularWhatsapp { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string QuemSomos { get; set; }
        public string Informativo { get; set; }
        public string Missao { get; set; }
        public string Visao { get; set; }
        public string Valores { get; set; }
        public bool Ativo { get; set; } = true;

        #endregion

        #region Relacionamentos
        public Guid ImagemId { get; set; }
        public Imagem Imagem { get; set; }
        #endregion

        #region Bidirecional
        public ICollection<Endereco> Enderecos { get; set; }
        public ICollection<RedeSocial> RedesSociais { get; set; }
        public ICollection<Parceiro> Parceiros { get; set; }
        public ICollection<Galeria> Galerias { get; set; }
        public ICollection<Mensagem> Mensagens { get; set; }
        public ICollection<Equipe> Equipes { get; set; }
        public ICollection<Usuario> Usuarios { get; set; }
        #endregion

        #region Crud
        EmpresaRepository _empresaRepositorio = new EmpresaRepository();
        public void Adicionar(Empresa empresa) => _empresaRepositorio.Adicionar(empresa);
        public void Atualizar(Empresa empresa) => _empresaRepositorio.Atualizar(empresa);
        public Empresa BuscarPorId(Guid empresaId) => _empresaRepositorio.BuscarPorId(empresaId);
        public IEnumerable<Empresa> BuscarTodosPorEmpresa(string textoDigitado) => _empresaRepositorio.BuscarTodosPorEmpresa(textoDigitado);
        public IEnumerable<Empresa> BuscarTodos() => _empresaRepositorio.BuscarTodos();
        public Empresa BuscarEmpresaParaTelaInicial() => _empresaRepositorio.BuscarEmpresaParaTelaInicial();
        #endregion

        #region Métodos
        public void AtivarOuDesativar()
        {
            Ativo = !Ativo;
        }

        public string CelularWhatsappFormat => $"55{CelularWhatsapp}";
        #endregion
    }
}

SiteSerralheriaSantos/Controllers/EmpresaController.cs
using PagedList;
using SiteSerralheriaSantos.Help;
using SiteSerralheriaSantos.Models;
using SiteSerralheriaSantos.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace SiteSerralheriaSantos.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly Empresa _empresa;
        private readonly Endereco _endereco;
        private readonly RedeSocial _redesocial;
        private readonly Imagem _imagem;
        private readonly Usuario _usuario;
        private readonly Mensagem _mensagem;

        public EmpresaController()
        {
            _empresa = new Empresa();
            _endereco = new Endereco();
            _redesocial = new RedeSocial();
            _imagem = new Imagem();
            _usuario = new Usuario();
            _mensagem = new Mensagem();
        }

        public ActionResult Index(int pagina = 1)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var empresas = _empresa.BuscarTodos();
            var lista = new List<Empresa>();
            lista.AddRange(empresas);
            return View(lista.ToPagedList(pagina, itensPorPagina));
        }

        public ActionResult AddOrUpdate()
        {
            var usuario = _usuario.BuscarPorId(Account.UsuarioId);
            var empresa = (usuario.EmpresaId == null) ? null : _empresa.BuscarPorId((Guid)usuario.EmpresaId);
            ViewBag.Empresa = (empresa == null) ? null : empresa;
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            if (usuario.EmpresaId == null)
                return RedirectToAction("Adicionar");
            else
                return RedirectToAction("Atualizar", new { empresaId = usuario.EmpresaId });
        }

        public ActionResult Adicionar()
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Empresa empresa, HttpPostedFileBase fotoLogo)
        {
            if (!ModelState.IsValid) return View(empresa).Error("Erro ao cadastrar empresa");
            if (fotoLogo != null)
            {
                var nomeDaImgDaLogo = Path.GetFileName(fotoLogo.FileName);
                var pathEmpresa = Path.Combine(Server.MapPath("~/Uploads/logo/"), nomeDaImgDaLogo);
                fotoLogo.SaveAs(pathEmpresa);
                var imagem = new Imagem();
                imagem.Url = imagem.CaminhoImgLogoEmpresa(fotoLogo.FileName);
                imagem.ImagemId = Guid.NewGuid();
                _imagem.Adicionar(imagem);
                empresa.ImagemId = imagem.ImagemId;
                empresa.EmpresaId = Guid.NewGuid();
                _empresa.Adicionar(empresa);
                var usuario = _usuario.BuscarPorId(Account.UsuarioId);
                if (usuario.EmpresaId == null && usuario.TipoUsuario == TipoUsuario.Administrador)
                {
                    usuario.EmpresaId = (Guid?)empresa.EmpresaId;
                    _usuario.Atualizar(usuario);
                }
                return RedirectToAction("Atualizar", new { empresaId = empresa.EmpresaId }).Success("Empresa cadastrado com sucesso");
            }
            else
            {
                return View(empresa).Error("Erro ao cadastrar empresa");
            }
        }

        public ActionResult Atualizar(Guid empresaId)
        {
            ViewBag.Mensagem = _mensagem.QntDeMsgNaoVisualizada();
            return View(_empresa.BuscarPorId(empresaId));
        }

        [HttpPost]
        public ActionResult Atualizar(Empresa empresa, HttpPostedFileBase fotoLogo)
        {
            if (!ModelState.IsValid) return View(empresa).Error("Erro ao atualizar empresa");
            if (fotoLogo == null)
            {
                _empresa.Atualizar(empresa);
                return RedirectToAction("Atualizar", new { empresaId = empresa.EmpresaId }).Success("Empresa atualizado com sucesso");
            }
            else
            {
                var nomeDaImgDaLogo = Path.GetFileName(fotoLogo.FileName);
                var pathEmpresa = Path.Combine(Server.MapPath("~/Uploads/logo/"), nomeDaImgDaLogo);
                fotoLogo.SaveAs(pathEmpresa);
                var imagem = _imagem.BuscarPorId(empresa.ImagemId);
                imagem.Url = imagem.CaminhoImgLogoEmpresa(fotoLogo.FileName);
                _imagem.Atualizar(imagem);
                _empresa.Atualizar(empresa);
                return RedirectToAction("Atualizar", new { empresaId = empresa.EmpresaId }).Success("Empresa atualizado com sucesso");
            }
        }

        public ActionResult Ativo(Guid empresaId, int pagina)
        {
            var empresaAtual = _empresa.BuscarPorId(empresaId);
            empresaAtual.AtivarOuDesativar();
            _empresa.Atualizar(empresaAtual);
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var empresas = _empresa.BuscarTodos();
            var lista = new List<Empresa>();
            lista.AddRange(empresas);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public PartialViewResult BuscarEmpresas(string textoDigitado, int pagina = 1)
        {
            TempData["Pagina"] = pagina;
            int itensPorPagina = 8;
            var empresas = _empresa.BuscarTodosPorEmpresa(textoDigitado);
            var lista = new List<Empresa>();
            lista.AddRange(empresas);
            return PartialView("_PartialTabela", lista.ToPagedList(pagina, itensPorPagina));
        }

        public ActionResult AbrirModalAdicionarEndereco()
        {
            return PartialView("_ModalAdicionarEndereco");
        }

        public ActionResult AbrirModalAdicionarRedeSocial()
        {
            return PartialView("_ModalAdicionarRedeSocial");
        }

        public ActionResult AbrirModalAtualizarEndereco(Guid enderecoId)
        {
            var endereco = _endereco.BuscarPorId(enderecoId);
            return PartialView("_ModalAtualizarEndereco", endereco);
        }

        public ActionResult AbrirModalAtualizarRedeSocial(Guid redesocialId)
        {
            var redesocial = _redesocial.BuscarPorId(redesocialId);
            return PartialView("_ModalAtualizarRedeSocial", redesocial);
        }

        [HttpPost]
        public ActionResult AdicionarEndereco(Endereco endereco)
        {
            _endereco.Adicionar(endereco);
            var enderecos = _endereco.BuscarTodosEnderecoPorEmpresa(endereco.EmpresaId);
            return PartialView("_PartialTabelaEndereco", enderecos);
        }

        [HttpPost]
        public ActionResult AdicionarRedeSocial(RedeSocial redesocial)
        {
            _redesocial.Adicionar(redesocial);
            var redesociais = _redesocial.BuscarTodosRedeSocialPorEmpresa(redesocial.EmpresaId);
            return PartialView("_PartialTabelaRedeSocial", redesociais);
        }

        [HttpPost]
        public ActionResult AtualizarEndereco(Endereco endereco)
        {
            _endereco.Atualizar(endereco);
            var enderecos = _endereco.BuscarTodosEnderecoPorEmpresa(endereco.EmpresaId);
            return PartialView("_PartialTabelaEndereco", enderecos);
        }

        [HttpPost]
        public ActionResult AtualizarRedeSocial(RedeSocial redesocial)
        {
            _redesocial.Atualizar(redesocial);
            var redesociais = _redesocial.BuscarTodosRedeSocialPorEmpresa(redesocial.EmpresaId);
            return PartialView("_PartialTabelaRedeSocial", redesociais);
        }

        public ActionResult AtivoEndereco(Guid enderecoId)
        {
            var enderecoAtual = _endereco.BuscarPorId(enderecoId);
            enderecoAtual.AtivarOuDesativar();
            _endereco.Atualizar(enderecoAtual);
            var enderecos = _endereco.BuscarTodosEnderecoPorEmpresa(enderecoAtual.EmpresaId);
            return PartialView("_PartialTabelaEndereco", enderecos);
        }

        public ActionResult AtivoRedeSocial(Guid redesocialId)
        {
            var redesocialAtual = _redesocial.BuscarPorId(redesocialId);
            redesocialAtual.AtivarOuDesativar();
            _redesocial.Atualizar(redesocialAtual);
            var redesociais = _redesocial.BuscarTodosRedeSocialPorEmpresa(redesocialAtual.EmpresaId);
            return PartialView("_PartialTabelaRedeSocial", redesociais);
        }
    }
}

SiteSerralheriaSantos/Views/Empresa/Adicionar.cshtml
@{
    ViewBag.Title = "Adicionar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
@section styles{
    @Styles.Render("~/Content/carregar-imagem")
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3><i>Empresa / Adicionar</i></h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content" style="display: block;">
                            <br>
                            @using (Html.BeginForm("Adicionar", "Empresa", FormMethod.Post, new { @class = "p-3 bg-white form-color", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Partial("_FormAdicionar")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/bundles/carregar-imagem")

    <script>
        $(document).on("keydown", "textarea", function () {
            objTextArea = this;
            while (objTextArea.scrollHeight > objTextArea.offsetHeight) {
                objTextArea.rows += 1;
            }
        });
    </script>
}

SiteSerralheriaSantos/Views/Empresa/Atualizar.cshtml
@model SiteSerralheriaSantos.Models.Empresa

@{
    ViewBag.Title = "Atualizar";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
@section styles{
    @Styles.Render("~/Content/carregar-imagem")
}
<section>
    <div class="container" style="margin-top:140px;">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3><i>Empresa / Atualizar</i></h3>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_content" style="display: block;">
                            <br>
                            @using (Html.BeginForm("Atualizar", "Empresa", FormMethod.Post, new { @class = "p-3 bg-white form-color", enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.HiddenFor(x => x.EmpresaId);
                                @Html.HiddenFor(x => x.ImagemId);
                                @Html.HiddenFor(x => x.Ativo);
                                @Html.Partial("_Form")
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade abrir-modal in"></div>
@section scripts{
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/bundles/carregar-modal")
    @Scripts.Render("~/bundles/add-or-update-endereco")
    @Scripts.Render("~/bundles/add-or-update-redesocial")
    @Scripts.Render("~/bundles/evento-ativo")
    @Scripts.Render("~/bundles/carregar-imagem")
    <script>
        $(document).on("keydown", "textarea", function () {
            objTextArea = this;
            while (objTextArea.scrollHeight > objTextArea.offsetHeight) {
                objTextArea.rows += 1;
            }
        });
    </script>
}

SiteSerralheriaSantos/Views/Empresa/_Form.cshtml
@using SiteSerralheriaSantos.ViewModels
@model SiteSerralheriaSantos.Models.Empresa
<div class="row form-group">
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Nome, new { @class = "" })
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-3 col-xs-12">
        @Html.LabelFor(model => model.Celular, new { @class = "" })
        @Html.TextBoxFor(model => model.Celular, new { @class = "form-control celular" })
        @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-3 col-xs-12">
        @Html.Label("Whatsapp")
        @Html.TextBoxFor(model => model.CelularWhatsapp, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CelularWhatsapp, "", new { @class = "text-danger" })
        <p style="font-size:9px; margin-bottom: -1rem;">Somente números</p>
    </div>
</div>
<div class="row form-group">
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Telefone, new { @class = "" })
        @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control telefone" })
        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Email, new { @class = "" })
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Missão")
        @Html.TextAreaFor(model => model.Missao, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Missao, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Visão")
        @Html.TextAreaFor(model => model.Visao, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Visao, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.LabelFor(model => model.Valores, new { @class = "" })
        @Html.TextAreaFor(model => model.Valores, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Valores, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.LabelFor(model => model.Informativo, new { @class = "" })
        @Html.TextAreaFor(model => model.Informativo, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Informativo, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Quem Somos")
        @Html.TextAreaFor(model => model.QuemSomos, new { @class = "form-control textArea", rows = "7" })
        @Html.ValidationMessageFor(model => model.QuemSomos, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12">
        @Html.Label("Imagem Logo")
        <div class="input-group image-preview">
            @if (Model == null || Model.ImagemId == null)
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="">
                <p style="font-size:9px; margin-bottom: -1rem;">Click dentro da caixa de texto</p>
            }
            else
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="@Url.Content(Model.Imagem.NomeImagemLogoEmpresa)">
                <p style="font-size:9px; margin-bottom: -1rem;">Click dentro da caixa de texto</p>
            }
            <span class="input-group-btn">
                <div class="btn btn-default image text-center">
                    <span class="glyphicon glyphicon-folder-open  glyphicon-align-center"></span>
                    <input type="file" name="fotoLogo" accept="image/png, image/jpeg, image/jpg" />
                </div>
            </span>
        </div>
    </div>
</div>
@if (Model != null)
{
    <div class="row form-group">
        <div class="col-md-2 text-center div-img">
            <img class="img-carregada" src="@Model.Imagem.Url" />
            <h4>@Model.Imagem.NomeImagemLogoEmpresa</h4>
        </div>
    </div>
}
<br />
<div class="row form-group">
    <div class="col-md-12">
        <button type="button" data-abrirmodal="@Url.Action("AbrirModalAdicionarRedeSocial", "Empresa", new { })" class="btn bg-secondary btn-abrirModal text-white">Adicionar Rede Social <i class="fa fa-plus"></i></button>
    </div>
</div>
<br />
<div class="tbl-redesocial">
    @if (Model.RedesSociais != null || Model.Enderecos.Any())
    {
        @Html.Partial("_PartialTabelaRedeSocial", Model.RedesSociais)
    }
    else
    {
        <div class="text-center">
            <h3>Nenhuma rede social cadastrada!</h3>
        </div>
    }
</div>
<br />
<div class="row form-group">
    <div class="col-md-12">
        <button type="button" data-abrirmodal="@Url.Action("AbrirModalAdicionarEndereco", "Empresa", new { })" class="btn bg-secondary btn-abrirModal text-white">Adicionar Endereço <i class="fa fa-plus"></i></button>
    </div>
</div>
<br />
<div class="tbl-endereco">
    @if (Model.Enderecos != null || Model.Enderecos.Any())
    {
        @Html.Partial("_PartialTabelaEndereco", Model.Enderecos)
    }
    else
    {
        <div class="text-center">
            <h3>Nenhum endereço cadastrado!</h3>
        </div>
    }
</div>
<hr />

<div class="row form-group">
    <div class="col-md-6">
        @if (Account.Roles == "Master")
        {
            <a href="@Url.Action("Index", "Empresa", new { })" class="btn bg-secondary text-white">Retornar</a>
        }
    </div>
    <div class="col-md-6 text-right">
        <input type="submit" value="Salvar" class="btn bg-secondary text-white">
    </div>
</div>

SiteSerralheriaSantos/Views/Empresa/_FormAdicionar.cshtml
@using SiteSerralheriaSantos.ViewModels
@model SiteSerralheriaSantos.Models.Empresa
<div class="row form-group">
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Nome, new { @class = "" })
        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-3 col-xs-12">
        @Html.LabelFor(model => model.Celular, new { @class = "" })
        @Html.TextBoxFor(model => model.Celular, new { @class = "form-control celular" })
        @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-3 col-xs-12">
        @Html.Label("Whatsapp")
        @Html.TextBoxFor(model => model.CelularWhatsapp, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CelularWhatsapp, "", new { @class = "text-danger" })
        <p style="font-size:9px; margin-bottom: -1rem;">Somente números</p>
    </div>
</div>
<div class="row form-group">
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Telefone, new { @class = "" })
        @Html.TextBoxFor(model => model.Telefone, new { @class = "form-control telefone" })
        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6 col-xs-12">
        @Html.LabelFor(model => model.Email, new { @class = "" })
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Missão")
        @Html.TextAreaFor(model => model.Missao, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Missao, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Visão")
        @Html.TextAreaFor(model => model.Visao, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Visao, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.LabelFor(model => model.Valores, new { @class = "" })
        @Html.TextAreaFor(model => model.Valores, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Valores, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.LabelFor(model => model.Informativo, new { @class = "" })
        @Html.TextAreaFor(model => model.Informativo, new { @class = "form-control textArea", rows = "4" })
        @Html.ValidationMessageFor(model => model.Informativo, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12 col-xs-12">
        @Html.Label("Quem Somos")
        @Html.TextAreaFor(model => model.QuemSomos, new { @class = "form-control textArea", rows = "7" })
        @Html.ValidationMessageFor(model => model.QuemSomos, "", new { @class = "text-danger" })
    </div>
</div>
<div class="row form-group">
    <div class="col-md-12">
        @Html.Label("Imagem Logo *")
        <div class="input-group image-preview">
            @if (Model == null || Model.ImagemId == null)
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="">
                <p style="font-size:9px; margin-bottom: -1rem;">Click dentro da caixa de texto</p>
            }
            else
            {
                <input type="text" class="form-control image-preview-filename" disabled="disabled" value="@Url.Content(Model.Imagem.NomeImagemLogoEmpresa)">
                <p style="font-size:9px; margin-bottom: -1rem;">Click dentro da caixa de texto</p>
            }
            <span class="input-group-btn">
                <div class="btn btn-default image text-center">
                    <span class="glyphicon glyphicon-folder-open  glyphicon-align-center"></span>
                    <input type="file" name="fotoLogo" accept="image/png, image/jpeg, image/jpg" />
                </div>
            </span>
        </div>
    </div>
</div>
@if (Model != null)
{
    <div class="row form-group">
        <div class="col-md-2 text-center div-img">
            <img class="img-carregada" src="@Model.Imagem.Url" />
            <h4>@Model.Imagem.NomeImagemLogoEmpresa</h4>
        </div>
    </div>
}
<hr />
<div class="row form-group">
    <div class="col-md-6">
        @if (Account.Roles == "Master")
        {
            <a href="@Url.Action("Index", "Empresa", new { })" class="btn bg-secondary text-white">Retornar</a>
        }
    </div>
    <div class="col-md-6 text-right">
        <input type="submit" value="Salvar" class="btn bg-secondary text-white">
    </div>
</div>

SiteSerralheriaSantos/Views/Empresa/_ModalAdicionarRedeSocial.cshtml
@model SiteSerralheriaSantos.Models.RedeSocial
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel2">Adicionar Rede Social</h4>
        </div>
        @using (Html.BeginForm("AdicionarRedeSocial", "Empresa", FormMethod.Post, new { id = "formAddRedeSocial" }))
        {
            <div class="modal-body">
                @Html.AntiForgeryToken()
                <div class="row form-group">
                    <div class="col-md-12">
                        @Html.Label("Tipo rede social")
                        @Html.EnumDropDownListFor(model => model.TipoRedeSocial, new { @class = "form-control", id = "titulo" })
                        @Html.ValidationMessageFor(model => model.TipoRedeSocial, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-12">
                        @Html.LabelFor(model => model.Link, new { })
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", id = "link" })
                        @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn bg-secondary text-white" data-dismiss="modal">Sair</button>
                <button type="button" id="btn-adicionar-redesocial" class="btn bg-secondary text-white">Confirmar</button>
            </div>
        }
    </div>
</div>

SiteSerralheriaSantos/Views/Empresa/_PartialTabelaEndereco.cshtml
@model IEnumerable<SiteSerralheriaSantos.Models.Endereco>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Rua</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Rua)
                </td>
                <td>
                    <button type="button" data-abrirmodal="@Url.Action("AbrirModalAtualizarEndereco", "Empresa", new { enderecoId = item.EnderecoId})" class="btn bg-secondary text-white fa fa-pencil btn-abrirModal" data-toggle="tooltip" title="Atualizar"></button>
                </td>
            </tr>
        }
    </tbody>
</table>